# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   namespace: rabbitmq-operator
#   name: rabbitmq-role
# rules:
#   - apiGroups: [""]
#     resources: ["pods", "services", "secrets", "configmaps", "endpoints"]
#     verbs: ["get", "list", "create", "update", "delete"]
#   - apiGroups: ["apps"]
#     resources: ["statefulsets"]
#     verbs: ["get", "list", "create", "update", "delete"]
#   - apiGroups: ["networking.k8s.io"]
#     resources: ["ingresses"]
#     verbs: ["get", "list", "create", "update", "delete"]
#   - apiGroups: ["cert-manager.io"]
#     resources: ["certificates", "issuers", "clusterissuers"]
#     verbs: ["get", "list", "create"]
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: rabbitmq-role-binding
#   namespace: rabbitmq-operator
# subjects:
#   - kind: ServiceAccount
#     name: default   # If using a different service account, replace 'default' with the name of your service account
#     namespace: rabbitmq-operator
# roleRef:
#   kind: Role
#   name: rabbitmq-role
#   apiGroup: rbac.authorization.k8s.io
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ServiceAccount
# metadata:
#   name: rabbitmq-service-account
#   namespace: rabbitmq-operator
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: rabbitmq-operator
  name: rabbitmq-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "secrets", "configmaps", "endpoints"]
    verbs: ["get", "list", "create", "update", "delete"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "list", "create", "update", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "create", "update", "delete"]
  - apiGroups: ["cert-manager.io"]
    resources: ["certificates", "issuers", "clusterissuers"]
    verbs: ["get", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rabbitmq-role-binding
  namespace: rabbitmq-operator
subjects:
  - kind: ServiceAccount
    name: default   # If using a different service account, replace 'default' with the name of your service account
    namespace: rabbitmq-operator
roleRef:
  kind: Role
  name: rabbitmq-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ServiceAccount
metadata:
  name: rabbitmq-service-account
  namespace: rabbitmq-operator
